apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: quickstart
  name: jenkins-deployment-manager
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-deployment-access
  namespace: quickstart
subjects:
  - kind: ServiceAccount
    name: jenkins-admin
    namespace: devops-tools # This is where the service account exists
roleRef:
  kind: Role
  name: jenkins-deployment-manager
  apiGroup: rbac.authorization.k8s.io
